name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

    Analysis:
      run-on: ubuntu-latest

      steps:
        -uses: action/checkout@v3
        -name: Build
        -run: ./mvnw clean package
        -name: Build docker image
        run: |
          docker build-t learningacademy .
          docker tag learningacademy gopal8686/learningacademy 
          docker push gopal8686/learningacademy:tagname